### ISSUE TITLE
install `k9s` on demand

### ISSUE THREAD

**Issue by petersutter** [gardener/ops-toolbelt#104]
**What would you like to be added**:
Similar to https://github.com/gardener/ops-toolbelt/pull/102, add install on demand script also for `k9s`

**Why is this needed**:

**Comment by mimiteto** [comment]
I saw that @etiennnr have done some `k9s` configuration tailored for Gardener.
Do we want to include it?

**Comment by petersutter** [comment]
fixed with #102
