### ISSUE TITLE
Hardcoded `etcd_host` is used as precalculated argument for `etcdctl --endpoints`

### ISSUE THREAD

**Issue by ishan16696** [gardener/ops-toolbelt#120]
**What happened**:
Right now, `etcd_host` is set to `etcd-main-local` and used as precalculated argument for `etcdctl --endpoints`.
https://github.com/gardener/ops-toolbelt/blob/d4e5d33af9b6bdd9a12ffc1a46463d16d5394b9f/install_on_demand/.etcdctl#L24
But, etcd's `endpoints` is not always necessary be `etcd-main-local` as we also have `etcd-events-*` pods which supports `etcd-events-local` as endpoints. Moreover, we also have `virtual-garden-etcd-events/main-*` which support `virtual-garden-etcd-main/events-local`. So, it can't be always `https://etcd-main-local:2379`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

**Comment by petersutter** [comment]
fixed with #119
