### ISSUE TITLE
Add crictl

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/ops-toolbelt#19]
**What would you like to be added**:

Consider adding the debugging tool [crictl](https://github.com/kubernetes-sigs/cri-tools) for CRI deamons. 
See the available functionality [here](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md).

**Why is this needed**:

Soon Gardener will have support for different ContainerRuntimes (gvisor & KataContainers) [see here](https://github.com/gardener/gardener/pull/2035).
The crictl tool could be a good addition to docker cli and ctr cli (when containerd is available).
- interact with a CRI runtime directly
- crictl offers a more kubernetes-friendly view of containers 
  -  knows about pods and namespace (docker does not),
  -  see Kubernetes pulled images. crtctl images lists the images available on a kubernetes node vs docker images list the images on the host know to docker. [See](https://kubernetes.io/blog/2018/05/24/kubernetes-containerd-integration-goes-ga/) 
- talks over the CRI interface - so "understands" all CRI compatible runtimes.

Note:

crictl per default connects to the dockershim on unix:///var/run/dockershim.sock. When running on a node that has CRI enabled (labels on node) then crictl should connect to the containerd socket
unix:///run/containerd/containerd.sock.

**Comment by danielfoehrKn** [comment]
Closing this for now as it might be better to add this tool on the Node Os image itself.

**Comment by neo-liang-sap** [comment]
i will work on this issue, please assign this to me, thanks!

**Comment by danielfoehrKn** [comment]
Thanks for taking care of it!

**Comment by neo-liang-sap** [comment]
PR opened https://github.com/gardener/ops-toolbelt/pull/21

**Comment by neo-liang-sap** [comment]
will open new ticket for adding nerdctl instead of crictl
/close

**Comment by vlerenc** [comment]
/reopen I am missing `crictl`. Could you please check why it's not (anymore?) in the image? I checked the non-suffix and the AWS/1.21 versions, but it's not there, I believe. Or am I wrong? Where should it be?

cc @neo-liang-sap @plkokanov @jfortin-sap

**Comment by plkokanov** [comment]
@vlerenc we only add `nerdctl` in the images, since it was decided that it's a bit more flexible and easier to use: https://github.com/gardener/ops-toolbelt/pull/21#issuecomment-871177059 

cc @petersutter
