### ISSUE TITLE
Provide Trimmed-Down Images per Infrastructure and Kubernetes Version

### ISSUE THREAD

**Issue by vlerenc** [gardener/ops-toolbelt#37]
**What would you like to be added**:
Today the images:
- are overly large (2x or 4x as large as the original first images; e.g. 200MB vs. 100MB for the plain toolbelt and 436MB vs. 116MB for the toolbelt with the `aws` CLI image)
- contain all infrastructures CLIs even though an operator needs usually only one (for a particular cluster)
- contains a 1.17 `kubectl`, which can be only used for clusters within the [skew policy](https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl), so is mostly the wrong one for the currently supported Kubernetes versions in Gardener

**Why is this needed**:
The current images are too large, not specific enough (which adds to the first problem and results in longer startup times and 2-4x higher network usage and costs), and features an outdated `kubectl` that may fail/will be useless for clusters of a particular version.

**What do you suggest**:
Let's:
1. First understand why the images became so large and what we can do to cut them down and get them smaller again (fewer components, cleanup, different base OS if it's not too disruptive)
2. Build a matrix of images (infrastructure x `kubectl` version), so that a user and the dashboard can pick the right one (gardener/dashboard#842) and of course also the big one (for local usage)

**Comment by vlerenc** [comment]
Thanks @jfortin-sap . 100 MB in general sounds great. I would be more reluctant to switch the base image to Alpine, if people got used to the current one. But the matrix will indeed be the big step towards smaller images.

**Comment by jfortin-sap** [comment]
Opened PR https://github.com/gardener/ops-toolbelt/pull/40
One of the changes, this will use vim-tiny instead of vim and only use .vimrc-minimal as .vimrc and remove the rest. kubectl edit still works.

**Comment by jfortin-sap** [comment]
I will look into whether we can replace the base OS image without too much complication.

**Comment by vlerenc** [comment]
@jfortin-sap @neo-liang-sap What is the status right now? With trimmed down images and with infrastructures CLIs (which really would be great to have)?

**Comment by vlerenc** [comment]
/ping @jfortin-sap @neo-liang-sap Trimmed down images that again contain the IaaS CLIs would be great to have.

**Comment by jfortin-sap** [comment]
@jfortin-sap I will look into it once done with other task.

**Comment by vlerenc** [comment]
Awesome, thanks @jfortin-sap . I would be great to have:
- Smaller images, so the web consoles and the local ops pods come up faster
- Have web consoles again with the IaaS CLIs embedded, so that I don't have to install them locally, possibly in different version

**Comment by jfortin-sap** [comment]
@vlerenc PR opened https://github.com/gardener/ops-toolbelt/pull/43

**Comment by petersutter** [comment]
/reopen

I guess this suggestion was not implemented:

> Build a matrix of images (infrastructure x kubectl version), so that a user and the dashboard can pick the right one (gardener/dashboard#842) and of course also the big one (for local usage)

**Comment by jfortin-sap** [comment]
@petersutter I'm on it
