### ISSUE TITLE
Scripts to ease work with terraform

### ISSUE THREAD

**Issue by plkokanov** [gardener/ops-toolbelt#7]
**What would you like to be added**:
We should add scripts that can ease work with terraform states.

**Why is this needed**:
Sometimes there are errors caused by terraform job pods:
1. A resource has already been created by a previous execution but the terraform state was not properly saved
1. There are resource leaks due to multiple executions of terraform jobs

To fix these the operator has to either manually delete the created resources on the cloud provider or manually update the terraform state configmaps kept in the Shoot's namespace on the Seed.

To ease this work we can introduce a couple of scripts which take care of automatically setting up the terraform work directory and properly updating the state's configmap.

**Comment by vlerenc** [comment]
That is/should actually be a convenient `gardenctl` feature. CC @DockToFuture .

**Comment by plkokanov** [comment]
Actually I was about to write it as an issue in gardenctl right before I wrote it in here.

**Comment by DockToFuture** [comment]
You can transfer this issue to ```gardenctl```.

**Comment by plkokanov** [comment]
Closing in favour of https://github.com/gardener/gardenctl/issues/134
